export const SERVICES_FETCH = 'SERVICES_FETCH'
export const SERVICES_FETCH_SUCCESS = 'SERVICES_FETCH_SUCCESS'
export const SERVICES_FETCH_FAILURE = 'SERVICES_FETCH_FAILURE'

export const CITATIONS_FETCH_SUCCESS = 'CITATIONS_FETCH_SUCCESS'
export const CITATIONS_FETCH_FAILURE = 'CITATIONS_FETCH_FAILURE'

export const SERVER_NOT_RESPONDING = 'SERVER_NOT_RESPONDING'
