export const SERVICES_FETCH_SUCCESS = 'SERVICES_FETCH_SUCCESS'
export const DNA_1D_SERVICES_FETCH_SUCCESS = 'DNA_1D_SERVICES_FETCH_SUCCESS'
export const DNA_2D_SERVICES_FETCH_SUCCESS = 'DNA_2D_SERVICES_FETCH_SUCCESS'
export const DNA_3D_SERVICES_FETCH_SUCCESS = 'DNA_3D_SERVICES_FETCH_SUCCESS'
export const DNA_XD_SERVICES_FETCH_SUCCESS = 'DNA_XD_SERVICES_FETCH_SUCCESS'

export const SERVICES_FETCH_FAILURE = 'SERVICES_FETCH_FAILURE'
export const DNA_1D_SERVICES_FETCH_FAILURE = 'DNA_1D_SERVICES_FETCH_FAILURE'
export const DNA_2D_SERVICES_FETCH_FAILURE = 'DNA_2D_SERVICES_FETCH_FAILURE'
export const DNA_3D_SERVICES_FETCH_FAILURE = 'DNA_3D_SERVICES_FETCH_FAILURE'
export const DNA_XD_SERVICES_FETCH_FAILURE = 'DNA_XD_SERVICES_FETCH_FAILURE'

export const SERVICES_FETCH = 'SERVICES_FETCH'

export const SERVER_NOT_RESPONDING = 'SERVER_NOT_RESPONDING'
